export enum MAP_CONSTANTS {
  MAX_ZOOM_FOR_SHOW_PINS = 6,
  ZOOM_LEVEL_FOR_CHANGE_STYLE_MARKER = 1,
  API_COUNT_TO_ENABLE_CLUSTERING = 100,
  NUMBER_OF_SIGNS = 10000000,
  ADDRESS_RADIUS_FOR_BBOX = 0.5, // km
  ZOOM_TO_MARKER_BUFFER = 0.1 // 20%
}

export const EARTH_RADIUS_KM = 6371
